## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - nightly

notifications:
  email: false

git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly

## uncomment the following lines to override the default test script
script:
 # rebuild sysimg for updating stdlib path info
 - julia -e 'include("contrib/build_sysimg.jl"); build_sysimg(force=true)'
 # build docs
 - cp -r zh_CN/* ./
 - julia -e 'include("doc/make.jl")'
 - julia --project --check-bounds=yes -e 'using Pkg; Pkg.activate(pwd()); Pkg.instantiate(); Pkg.build(); Pkg.test(; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
