# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# os:
#   - linux
#   - osx
# julia:
#   - 1.0
#   - 1.1
#   - nightly
# matrix:
#   allow_failures:
#     - julia: nightly
#   fast_finish: true
notifications:
  email: false
# after_success:
#   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
#   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

env:
  global:
    - DOCUMENTER_DEBUG=true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - docker version
        - julia -e 'include("contrib/build_sysimg.jl"); build_sysimg(force=true)'
        - julia --project=doc/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=doc/ doc/make.jl deploy
        - travis_wait 30 julia --project=doc/ doc/make.jl pdf texplatform=docker
      services: docker

deploy:
  provider: releases
  api_key:
    secure: nbJnBdbv1Murzv0mQZfTShP6oqFRreQw7h9f5+xdQkN1JaIqhb3rqXrpVRYUdZ70f+PaX5dUfJbtLhBpXWGIFmNEUQxbK7nD9av+ao9wFJVM4buzb1zbdjfkgtu98Hwc+Om/87Q32tCO7455OYnOjM+ilvsMoJAR5RiXFvd1URuB3zy6zBEFWIaf4ILS8BbuCMduWIgWEYUdLE4+O+9jy91HTV5VibBWRB0sJHgLPb0RWVYuICRwB3KNHqXNnLThq2VOEWGJPKQ8/zCsv1Pw3gMw6FWpKsvDfHkLznh8ZeJ2OJGTS+rAb1ExO+ALAzhTGbBZFbThGKP9xjP6UeOjilyjh86Oqb9fkegNXA9nPQ/9eiD2Zc+Y6ZN4/cM5Ao47wYUzfwlfDs1kcze0b6PNatHVA2yzwndukG+sO9V+LPF6praGyn1GJ7Ctt5+doILPGPQh6Gm6awwSYnySd3CPO97cZ/zyLJ8MQS7E+1pEb5TFyw5nRzSaSUxgi7thQhVDU3xWEyangFtfNqT++FHeq4pAwz2kAzqBcFf3sIRVgYHuPt7x8HYB7S4XTjLMB5QsfoEM+CPl/My0+xYB/pJ+vImznupVlcbgNFJWHM1r472ZG0jT6l+n39+zyBrvsSTK3jZ6L9LPvlduZyH5aX4lteJB2sYU8Erl+DzXgQRALB4=
  file: doc/build/Julia中文文档.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JuliaCN/JuliaZH.jl
